project:
  type: website

website:
  title: "htoisanroi.github.io"
  navbar:
    left:
      - href: about.qmd
        text: About

      - href: Tryphosa CV.pdf
        text: Resume

      - href: research.qmd
        text: Research

      - text: EPPS 6323
        menu:
          - text: Project Presentation
            href: project.qmd

          - text: Final Project Pdf
            href: finalproject.qmd

          - text: Project Proposal Presentation
            href: projectproposal.qmd

          - text: Assignment 1
            href: epps6323assignment1.qmd

          - text: Assignment 2
            href: epps6323assignment2.qmd

          - text: Assignment 3
            href: epps6323assignment3.qmd

          - text: Assignment 4
            href: epps6323assignment4.qmd

          - text: Lab 1
            href: epps6323lab1.qmd
            
          - text: Lab 2
            href: epps6323lab2.qmd

format:
  html:
    theme: yeti
    css: bootstrap.css
    toc: true

editor: visual